#' Simulate one stepped-wedge trial dataset
#'
#' Generates aggregated provider-by-step binomial data for a stepped-wedge
#' design in which specialty groups cross over sequentially.
#'
#' @param effect_size_or Odds ratio for treatment under the data-generating
#'   model.
#' @param n_providers_per_specialty Integer vector giving the number of providers
#'   in each specialty.
#' @param specialty_names Labels for the specialty groups.
#' @param tau_provider Standard deviation of the provider random intercept.
#' @param base_probs Baseline testing probabilities for each specialty.
#' @param pts_per_step Number of patients per provider per study step.
#' @param n_steps Number of study steps. The default is one baseline period plus
#'   one crossover period per specialty.
#' @param seed Optional random seed.
#'
#' @return A data frame with one row per provider-step combination.
#' @export
simulate_stepwedge_trial <- function(
  effect_size_or = 1.5,
  n_providers_per_specialty = c(40, 40, 40, 40),
  specialty_names = c("Cardiol", "IntMed", "FamMed", "Neurol"),
  tau_provider = 1.21,
  base_probs = c(0.06, 0.04, 0.03, 0.02),
  pts_per_step = 20,
  n_steps = length(n_providers_per_specialty) + 1L,
  seed = NULL
) {
  if (!is.null(seed)) {
    set.seed(seed)
  }

  if (length(n_providers_per_specialty) != length(base_probs)) {
    stop("n_providers_per_specialty and base_probs must have the same length.", call. = FALSE)
  }

  if (length(specialty_names) != length(n_providers_per_specialty)) {
    stop("specialty_names must have the same length as n_providers_per_specialty.", call. = FALSE)
  }

  total_providers <- sum(n_providers_per_specialty)
  specialty_idx <- rep(seq_along(n_providers_per_specialty), times = n_providers_per_specialty)

  prov_df <- data.frame(
    PID = seq_len(total_providers),
    specialty_idx = specialty_idx,
    specialty = specialty_names[specialty_idx],
    b_i = stats::rnorm(total_providers, mean = 0, sd = tau_provider),
    stringsAsFactors = FALSE
  )

  sim_data <- merge(
    prov_df,
    data.frame(step = seq_len(n_steps)),
    by = NULL
  )

  sim_data$treat <- as.integer(sim_data$step > sim_data$specialty_idx)
  sim_data$n_patients <- pts_per_step

  base_intercepts <- stats::qlogis(base_probs)
  sim_data$base_logit <- base_intercepts[sim_data$specialty_idx]
  sim_data$true_logit <- sim_data$base_logit + log(effect_size_or) * sim_data$treat + sim_data$b_i
  sim_data$true_prob <- stats::plogis(sim_data$true_logit)
  sim_data$n_positive <- stats::rbinom(
    n = nrow(sim_data),
    size = sim_data$n_patients,
    prob = sim_data$true_prob
  )

  sim_data[order(sim_data$PID, sim_data$step), , drop = FALSE]
}

#' Fit the stepped-wedge analysis model to a simulated dataset
#'
#' Fits the mixed-effects model used in the original script and extracts the
#' treatment p-value.
#'
#' @param sim_data A data frame generated by \code{\link{simulate_stepwedge_trial}}
#'   or a compatible aggregated provider-step dataset.
#' @param fit_link Link function used in the fitted model.
#' @param nAGQ Number of quadrature points for \code{lme4::glmer()}.
#'
#' @return A list with fitted model, treatment coefficient table, and p-value.
#' @export
run_stepwedge_analysis <- function(
  sim_data,
  fit_link = c("logit", "identity"),
  nAGQ = 1
) {
  fit_link <- match.arg(fit_link)
  .check_required_columns(
    sim_data,
    c("n_positive", "n_patients", "treat", "step", "specialty_idx", "PID")
  )

  fit <- tryCatch(
    lme4::glmer(
      cbind(n_positive, n_patients - n_positive) ~
        treat + factor(step) + factor(specialty_idx) + (1 | PID),
      family = stats::binomial(link = fit_link),
      data = sim_data,
      nAGQ = nAGQ
    ),
    error = function(e) NULL
  )

  if (is.null(fit)) {
    return(list(fit = NULL, coefficients = NULL, p_value = NA_real_))
  }

  coefs <- summary(fit)$coefficients
  p_value <- if ("treat" %in% rownames(coefs)) coefs["treat", "Pr(>|z|)"] else NA_real_

  list(
    fit = fit,
    coefficients = coefs,
    p_value = as.numeric(p_value)
  )
}

#' Estimate power by repeated stepped-wedge simulation
#'
#' Repeats the stepped-wedge simulation-and-analysis workflow and estimates the
#' rejection probability at level \code{alpha}.
#'
#' @param n_simulations Number of simulations.
#' @param alpha Significance threshold.
#' @param effect_size_or Odds ratio under the data-generating model.
#' @param n_providers_per_specialty Integer vector of provider counts by
#'   specialty.
#' @param specialty_names Labels for the specialty groups.
#' @param tau_provider Standard deviation of the provider random intercept.
#' @param base_probs Baseline testing probabilities by specialty.
#' @param pts_per_step Patients per provider per study step.
#' @param n_steps Number of study steps.
#' @param fit_link Link used when fitting the analysis model.
#' @param seed Optional seed.
#' @param nAGQ Number of quadrature points for the fitted mixed model.
#'
#' @return A list with estimated power and the simulation p-values.
#' @export
estimate_power <- function(
  n_simulations = 100,
  alpha = 0.05,
  effect_size_or = 2,
  n_providers_per_specialty = c(40, 40, 40, 40) * 0.25,
  specialty_names = c("Cardiol", "IntMed", "FamMed", "Neurol"),
  tau_provider = 1.21,
  base_probs = c(0.07, 0.04, 0.03, 0.02),
  pts_per_step = 100 / 5,
  n_steps = length(n_providers_per_specialty) + 1L,
  fit_link = c("logit", "identity"),
  seed = NULL,
  nAGQ = 1
) {
  fit_link <- match.arg(fit_link)

  if (!is.null(seed)) {
    set.seed(seed)
  }

  p_values <- rep(NA_real_, n_simulations)

  for (i in seq_len(n_simulations)) {
    sim_data <- simulate_stepwedge_trial(
      effect_size_or = effect_size_or,
      n_providers_per_specialty = n_providers_per_specialty,
      specialty_names = specialty_names,
      tau_provider = tau_provider,
      base_probs = base_probs,
      pts_per_step = pts_per_step,
      n_steps = n_steps
    )
    analysis <- run_stepwedge_analysis(sim_data, fit_link = fit_link, nAGQ = nAGQ)
    p_values[i] <- analysis$p_value
  }

  power_est <- mean(p_values < alpha, na.rm = TRUE)

  list(
    call = match.call(),
    power = power_est,
    alpha = alpha,
    p_values = p_values,
    n_successful = sum(!is.na(p_values)),
    n_failed = sum(is.na(p_values))
  )
}

#' Estimate type I error by repeated stepped-wedge simulation
#'
#' A convenience wrapper around \code{\link{estimate_power}} that sets the
#' treatment odds ratio to 1.
#'
#' @inheritParams estimate_power
#'
#' @return A list like \code{\link{estimate_power}}, with \code$type1_error}
#'   added.
#' @export
estimate_type1_error <- function(
  n_simulations = 100,
  alpha = 0.05,
  n_providers_per_specialty = c(40, 40, 40, 40) * 0.25,
  specialty_names = c("Cardiol", "IntMed", "FamMed", "Neurol"),
  tau_provider = 1.21,
  base_probs = c(0.07, 0.04, 0.03, 0.02),
  pts_per_step = 100 / 5,
  n_steps = length(n_providers_per_specialty) + 1L,
  fit_link = c("logit", "identity"),
  seed = NULL,
  nAGQ = 1
) {
  fit_link <- match.arg(fit_link)

  out <- estimate_power(
    n_simulations = n_simulations,
    alpha = alpha,
    effect_size_or = 1,
    n_providers_per_specialty = n_providers_per_specialty,
    specialty_names = specialty_names,
    tau_provider = tau_provider,
    base_probs = base_probs,
    pts_per_step = pts_per_step,
    n_steps = n_steps,
    fit_link = fit_link,
    seed = seed,
    nAGQ = nAGQ
  )
  out$type1_error <- out$power
  out
}
